version: "2.2"
networks:
    app-tier:
      driver: bridge
services:
    # web-ui:
    #     image: home-automation-client:latest
    #     ports:
    #         - "4200:4200"
    mongo:
        image: mongo:latest
        ports:
            - "27018:27017"
        volumes:
            - ../mongo_data:/data/db
        networks:
            - "app-tier"
        restart: always
    es:
        image: bitnami/elasticsearch:latest
        ports:
            - "9201:9200"
        volumes:
            - ../es_data:/bitnami/elasticsearch/data
        networks:
            - "app-tier"
    # es01:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    #     container_name: es01
    #     environment:
    #       - node.name=es01
    #       - cluster.name=es-docker-cluster
    #       - discovery.seed_hosts=es02,es03
    #       - cluster.initial_master_nodes=es01,es02,es03
    #       - bootstrap.memory_lock=true
    #       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #     ulimits:
    #       memlock:
    #         soft: -1
    #         hard: -1
    #     volumes:
    #       - data01:/usr/share/elasticsearch/data
    #     ports:
    #       - 9200:9200
    #     networks:
    #       - elastic

    # es02:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    #     container_name: es02
    #     environment:
    #       - node.name=es02
    #       - cluster.name=es-docker-cluster
    #       - discovery.seed_hosts=es01,es03
    #       - cluster.initial_master_nodes=es01,es02,es03
    #       - bootstrap.memory_lock=true
    #       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #     ulimits:
    #       memlock:
    #         soft: -1
    #         hard: -1
    #     volumes:
    #       - data02:/usr/share/elasticsearch/data
    #     networks:
    #       - elastic

    # es03:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    #     container_name: es03
    #     environment:
    #       - node.name=es03
    #       - cluster.name=es-docker-cluster
    #       - discovery.seed_hosts=es01,es02
    #       - cluster.initial_master_nodes=es01,es02,es03
    #       - bootstrap.memory_lock=true
    #       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    #     ulimits:
    #       memlock:
    #         soft: -1
    #         hard: -1
    #     volumes:
    #       - data03:/usr/share/elasticsearch/data
    #     networks:
    #       - elastic

    #     #   kib01:
    #     #     image: docker.elastic.co/kibana/kibana:7.13.3
    #     #     container_name: kib01
    #     #     ports:
    #     #       - 5601:5601
    #     #     environment:
    #     #       ELASTICSEARCH_URL: http://es01:9200
    #     #       ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
    #     #     networks:
    #     #       - elastic


    web-api:
        build: .
        ports:
            - "3000:3000"
        networks:
            - "app-tier"
        depends_on:
            - mongo
            - es
        env_file:
            - ./.env

# volumes:
#     data01:
#       driver: local
#     data02:
#       driver: local
#     data03:
#       driver: local
# networks:
#     elastic:
#       driver: bridge
